"""
Kickstart tool to generate custom evaluation scripts for MCP tools.

This creates a boilerplate evaluation script that users can customize
for their specific MCP tools and run standalone or in CI pipelines.
"""

import argparse
import sys
from pathlib import Path

EVAL_SCRIPT_TEMPLATE = '''#!/usr/bin/env python
"""
MCP Tool Evaluation Script

Generated by toolvaluator-init

This script evaluates how well language models use your MCP tools.
Customize the examples below to match your specific tools and use cases.

Usage:
    python {output_filename} --model gpt-4o-mini
    python {output_filename} --model local-model --base-url http://localhost:1234/v1 --api-key local
    python {output_filename} --model gpt-4o --min-score 0.85  # For CI/CD
"""

import argparse
import os
import sys

import dspy
from toolvaluator import eval_model, extract_input_schema, extract_tool_description, get_tool_schemas_sync

# Import your MCP server
from {server_module} import {server_var}


def build_evaluation_dataset(tool_schemas):
    """
    Create evaluation examples for your MCP tools.

    Each example tests whether the model can correctly:
    1. Decide when to call a tool (should_call)
    2. Choose the right tool (tool_name)
    3. Extract the correct arguments (arguments)

    Args:
        tool_schemas: Dict mapping tool names to their schemas

    Returns:
        List of dspy.Example objects
    """
    examples = []

    # Example format (uncomment and customize):
    # if "your_tool_name" in tool_schemas:
    #     tool_name = "your_tool_name"
    #     tool_description = extract_tool_description(tool_schemas[tool_name])
    #     tool_schema = extract_input_schema(tool_schemas[tool_name])
    #
    #     # Positive example - should use the tool
    #     examples.append(
    #         dspy.Example(
    #             user_query="Natural language query that should trigger this tool",
    #             tool_name=tool_name,  # Name of the tool
    #             tool_description=tool_description,  # What the tool does
    #             tool_schema=tool_schema,  # Parameter schema
    #             expected_should_call=True,  # Should the model call this tool?
    #             expected_tool_name=tool_name,  # Which tool should be called?
    #             expected_arguments={{  # What arguments should be extracted?
    #                 "arg1": "expected_value1",
    #                 "arg2": 123,
    #             }},
    #         ).with_inputs("user_query", "tool_name", "tool_description", "tool_schema")
    #     )
    #
    #     # Negative example - should NOT use the tool
    #     examples.append(
    #         dspy.Example(
    #             user_query="A query that doesn't need this tool",
    #             tool_name=tool_name,
    #             tool_description=tool_description,
    #             tool_schema=tool_schema,
    #             expected_should_call=False,  # Model should answer directly
    #             expected_tool_name="",
    #             expected_arguments={{}},
    #         ).with_inputs("user_query", "tool_name", "tool_description", "tool_schema")
    #     )

    # TODO: Customize these examples for your tools!
    # Below are auto-generated templates - replace with your actual use cases

{tool_examples}

    if not examples:
        print("WARNING: No evaluation examples defined!")
        print("Edit this script and add examples for your tools in build_evaluation_dataset()")

    return examples


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate LLM performance on your MCP tools"
    )
    parser.add_argument(
        "--model",
        type=str,
        default="gpt-4o-mini",
        help="Model name (e.g., gpt-4o-mini, or local-model for LM Studio)",
    )
    parser.add_argument(
        "--api-key",
        type=str,
        default=None,
        help="API key for the model (defaults to OPENAI_API_KEY env var)",
    )
    parser.add_argument(
        "--base-url",
        type=str,
        default=None,
        help="Base URL for OpenAI-compatible endpoints (e.g., http://localhost:1234/v1)",
    )
    parser.add_argument(
        "--min-score",
        type=float,
        default=0.0,
        help="Minimum acceptable score (0-1). Exit with error if below this.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Show detailed debug information for each example",
    )
    args = parser.parse_args()

    # Get API key
    api_key = args.api_key or os.getenv("OPENAI_API_KEY")
    if not api_key and not args.base_url:
        print("ERROR: No API key provided.", file=sys.stderr)
        print("Set OPENAI_API_KEY or use --api-key or --base-url", file=sys.stderr)
        sys.exit(1)

    # Fetch tool schemas from your MCP server
    print("Fetching tool schemas from MCP server...")
    tool_schemas = get_tool_schemas_sync({server_var})

    if not tool_schemas:
        print("ERROR: No tools found on MCP server!", file=sys.stderr)
        sys.exit(1)

    print(f"Found tools: {{', '.join(tool_schemas.keys())}}")

    # Build evaluation dataset
    dataset = build_evaluation_dataset(tool_schemas)

    if not dataset:
        print("ERROR: No evaluation examples defined!", file=sys.stderr)
        print("Edit this script and add examples in build_evaluation_dataset()", file=sys.stderr)
        sys.exit(1)

    print(f"Running evaluation with {{len(dataset)}} examples...\\n")

    # Run evaluation
    result = eval_model(
        model_name=args.model,
        api_key=api_key,
        base_url=args.base_url,
        dataset=dataset,
        verbose=args.verbose,
    )

    # Check results
    score = result["score"]
    if score < args.min_score:
        print(f"\\nFAIL: Score {{score:.3f}} < minimum {{args.min_score:.3f}}")
        sys.exit(1)
    else:
        print(f"\\nPASS: Score {{score:.3f}} >= minimum {{args.min_score:.3f}}")
        sys.exit(0)


if __name__ == "__main__":
    main()
'''


def generate_tool_examples(tool_names, indent="    "):
    """Generate template examples for the given tool names."""
    if not tool_names:
        return f'{indent}# Add examples for your tools here\n{indent}pass'

    examples = []
    for tool_name in tool_names:
        example = f'''
{indent}# Example for '{tool_name}' tool
{indent}if "{tool_name}" in tool_schemas:
{indent}    tool_name = "{tool_name}"
{indent}    tool_description = extract_tool_description(tool_schemas[tool_name])
{indent}    tool_schema = extract_input_schema(tool_schemas[tool_name])
{indent}
{indent}    # TODO: Customize this example for your tool
{indent}    examples.append(
{indent}        dspy.Example(
{indent}            user_query="Your test query that should use {tool_name}",
{indent}            tool_name=tool_name,
{indent}            tool_description=tool_description,
{indent}            tool_schema=tool_schema,
{indent}            expected_should_call=True,
{indent}            expected_tool_name=tool_name,
{indent}            expected_arguments={{
{indent}                # TODO: Add expected argument names and values
{indent}                # "arg_name": "expected_value",
{indent}            }},
{indent}        ).with_inputs("user_query", "tool_name", "tool_description", "tool_schema")
{indent}    )
{indent}
{indent}    # Negative test case (should NOT use the tool)
{indent}    examples.append(
{indent}        dspy.Example(
{indent}            user_query="A question that doesn't need {tool_name}",
{indent}            tool_name=tool_name,
{indent}            tool_description=tool_description,
{indent}            tool_schema=tool_schema,
{indent}            expected_should_call=False,
{indent}            expected_tool_name="",
{indent}            expected_arguments={{}},
{indent}        ).with_inputs("user_query", "tool_name", "tool_description", "tool_schema")
{indent}    )
'''
        examples.append(example)

    return '\n'.join(examples)


def detect_tools_from_server(server_module, server_var):
    """Try to detect tool names from the server module."""
    try:
        import importlib

        from toolvaluator import get_tool_schemas_sync

        mod = importlib.import_module(server_module)
        server = getattr(mod, server_var)
        tool_schemas = get_tool_schemas_sync(server)
        return list(tool_schemas.keys())
    except Exception as e:
        print(f"Warning: Could not auto-detect tools: {e}", file=sys.stderr)
        return []


def main():
    parser = argparse.ArgumentParser(
        description="Generate a custom evaluation script for your MCP tools",
        epilog="Example: toolvaluator-init --server my_server --output eval_my_tools.py"
    )
    parser.add_argument(
        "--server",
        type=str,
        required=True,
        help="Python module containing your MCP server (e.g., 'my_server')",
    )
    parser.add_argument(
        "--server-var",
        type=str,
        default="mcp",
        help="Name of the FastMCP instance variable (default: 'mcp')",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        default="eval_tools.py",
        help="Output filename for the generated script (default: eval_tools.py)",
    )
    parser.add_argument(
        "--tools",
        type=str,
        nargs="*",
        help="Tool names to generate examples for (auto-detected if not specified)",
    )
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Overwrite output file if it exists",
    )
    args = parser.parse_args()

    # Check if output file exists
    output_path = Path(args.output)
    if output_path.exists() and not args.force:
        print(f"ERROR: Output file '{args.output}' already exists!", file=sys.stderr)
        print("Use --force to overwrite, or specify a different --output filename", file=sys.stderr)
        sys.exit(1)

    # Detect or use provided tool names
    tool_names = args.tools
    if not tool_names:
        print(f"Auto-detecting tools from {args.server}.{args.server_var}...")
        tool_names = detect_tools_from_server(args.server, args.server_var)
        if tool_names:
            print(f"Detected tools: {', '.join(tool_names)}")
        else:
            print("Warning: Could not auto-detect tools. Generating empty template.")
            tool_names = []

    # Generate tool examples
    tool_examples = generate_tool_examples(tool_names)

    # Generate the script
    script_content = EVAL_SCRIPT_TEMPLATE.format(
        output_filename=args.output,
        server_module=args.server,
        server_var=args.server_var,
        tool_examples=tool_examples,
    )

    # Write the script
    output_path.write_text(script_content)
    output_path.chmod(0o755)  # Make executable

    print(f"\nGenerated evaluation script: {args.output}")
    print("\nNext steps:")
    print(f"  1. Edit {args.output} and customize the evaluation examples")
    print("  2. Run the evaluation:")
    print(f"     python {args.output} --model gpt-4o-mini --verbose")
    print("  3. Use in CI/CD with --min-score:")
    print(f"     python {args.output} --model gpt-4o --min-score 0.85")


if __name__ == "__main__":
    main()
